name: easy_image_viewer
description: An easy image viewer with pinch & zoom, multi image, and built-in
  full-screen dialog support.
version: 1.1.0
homepage: https://github.com/thesmythgroup/easy_image_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dots_indicator: ^2.1.0
  page_view_dot_indicator: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
